ENV:
  sim_path: ''
  ground_truth_mode: false
  metadata_port: 9007
  image_port: 9008

EPISODE:
  scenes: [3, 4, 5, 5]
  n_targets: [30, 30, 30, 30]
  episode_length: [400, 400, 400, 400]
  random_seeds: [10, 1, 5, 6]
